### ISSUE TITLE
midi_io.py told me that the Temp directory doesn't have permissions on Windows

### ISSUE THREAD

**Issue by MizoTake** [magenta/note-seq#16]
got an error like this

```
Traceback (most recent call last):
  File "scripts/models/generate_midi.py", line 69, in <module>
    tf.app.run(main)
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Python36\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Python36\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "scripts/models/generate_midi.py", line 59, in main
    mg.run_with_flags(generator)
  File "C:\Python36\lib\site-packages\magenta\models\melody_rnn\melody_rnn_generate.py", line 214, in run_with_flags
    note_seq.sequence_proto_to_midi_file(generated_sequence, midi_path)
  File "C:\Python36\lib\site-packages\note_seq\midi_io.py", line 372, in sequence_proto_to_midi_file
    drop_events_n_seconds_after_last_note)
  File "C:\Python36\lib\site-packages\note_seq\midi_io.py", line 217, in note_sequence_to_midi_file
    copyfile(temp_file.name, output_file)
  File "C:\Python36\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\%USERNAME%\\AppData\\Local\\Temp\\tmpdgf5fwq_'
```

I tried to confirm

https://github.com/magenta/note-seq/blob/master/note_seq/midi_io.py#L211

`  with tempfile.NamedTemporaryFile() as temp_file:`

↓

`  with tempfile.NamedTemporaryFile(delete=False) as temp_file:`

this works as you want it to work. didn't get an error.

**Comment by douglaseck** [comment]
If we use the delete=False flag, we won't trigger this error, but I presume
our temporary files will pile up. They're so small it's probably not an
issue. I wonder, however, is it possible there are some permissions
problems? I haven't seen this problem before.

Could you try a small test program (not using Magenta at all) that tries to
create a file using
"with tempfile.NamedTemporaryFile() as temp_file:".

I believe that should work in general, so if it fails on your machine there
may be an upstream issue.

**Comment by MizoTake** [comment]
I investigated the fundamental solution. It seems to be a `magenta` problem rather than `note_seq` in the processing flow.

https://docs.python.org/ja/3.6/library/tempfile.html#tempfile.NamedTemporaryFile
> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

will make sure to check the magenta issue. Thank you.

**Comment by cghawthorne** [comment]
pretty_midi now supports writing to a filehandle directly, so I don't think we even need the temp file anymore. I can take a look.

**Comment by MizoTake** [comment]
I've adapted the pull request above and confirmed that it works on Windows. Thanks.
