### ISSUE TITLE
NoteSequence not picklable

### ISSUE THREAD

**Issue by cifkao** [magenta/note-seq#2]
(Originally magenta/magenta#1733.)

When trying to pickle a `NoteSequence` (which happens e.g. when using `multiprocessing`), the following error comes up:
```
PicklingError: Can't pickle <class 'music_pb2.NoteSequence'>: import of module 'music_pb2' failed
```
It seems related to [this](https://groups.google.com/d/msg/protobuf/4hcUwzlweYs/i8yqvujZTVMJ) (old) protobuf issue.

However, it seems that some protobuffers (e.g. `tf.GraphDef`) can be pickled, so it might be just a matter of using a more recent version of protoc or passing the right flag to it? Or maybe it's a namespace naming issue?

**Comment by cghawthorne** [comment]
Do you have some code to reproduce this? I was able to do this without any issues:

```
ns = note_seq.NoteSequence(filename='foo')
pickle.loads(pickle.dumps(ns))
```
Output:
```
filename: "foo"
```

**Comment by cifkao** [comment]
I'm able to reproduce the error with your code in a clean virtual environment with Python 3.6 and `note-seq==0.0.0` installed with `pip`.

**Comment by cghawthorne** [comment]
Sorry for the delay, the problem didn't show up with our internal proto code generation process, which is why I didn't see the problem at first!
