### ISSUE TITLE
File PermissionError at Midi File output (Python3, Win7)

### ISSUE THREAD

**Issue by CircuV** [magenta/note-seq#21]
I'm getting the following error on a performance_rnn_generate run (on Magenta Python3 Win7):
Seems to occur when trying to output the generated Midi file. Don't know
why it tris to create a File in Temp before writing to the final destination.

  File "d:\programme\anaconda3\envs\magenta\lib\site-packages\pretty_midi\pretty
_midi.py", line 1374, in write
    mid.save(filename=filename)
  File "d:\programme\anaconda3\envs\magenta\lib\site-packages\mido\midifiles\mid
ifiles.py", line 409, in save
    with io.open(filename, 'wb') as file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Cv\\AppData\\Local\
\Temp\\tmpkh_zo2m3'

Even I run it in as admin

**Comment by cghawthorne** [comment]
This is now a duplicate of #16, which has been fixed and will be available in the next version of the pip package.
